# Intro

Start with story of how Mal recognized PDF template
- Image of PDF template
- Transition to X over PDF template

R users are not graphic designers
- Art school vs data school? 
- Or cool designer vs nerdy data person?

Two extremes: 

1. Ugly reports made in R

- Image of PDF template

2. Highly produced docs made by graphic designer

- Take something from Behance


# PSC

Story of how they came to me (the horror of generating 170 highly stylized reports)

- Animated map with progressively faster dots dropping on map

HTML is great, but many people still want something they can read so they need PDFs

- Yeah, I'm gonna need that in a PDF
- https://www.workfront.com/sites/default/files/imported/400867961-11778.jpg

pagedown is great because it's not LaTeX!

- Images of people hating on LaTeX

Thomas and I produce highly stylized, but custom templates with pagedown

- Image of OMNI
- Image of PSC

# Can others make pagedown templates?

Problem is you need to know HTML + CSS well to really work with pagedown

- Talk about my office hours session trying to show how to customize a few things

How can we make something that other R users can adapt and use?

- It's YAML all the way down

# pagedreport

Overview

- Slide with images of each template

All customization in YAML

- Show YAML

Demo one template

- Switch to RStudio

# Conclusion

Don't do ugly PDFs

If you want to do fully customizable PDFs, use pagedown

If you want something simple, use pagedreport

